[tool.poetry]
name = "yelp_nlp"
version = "0.1.0"
description = "sentiment model based on yelp"
authors = ["epy <eddiepyang@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
attrs = "^21.4.0"
numpy = ">=1.18.3"
pandas = "^1.4.2"
torch = "^1.08.0"
seaborn = "^0.11.2"
spacy = "^3.2.4"
gensim = "^4.1.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
